name: 1일 1커밋 자동화

on:
  schedule:
    # 매일 오전 12시에 실행 (UTC 기준) : 분 시 일 월 요일
    - cron: "0 0 * * *"

jobs:
  push-daily-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # 전체 커밋 히스토리를 가져옴

      - name: Configure Git
        run: |
          git config user.name "DevNerd"
          git config user.email "krsy0411@naver.com"

      - name: Push one commit per day
        run: |
          # origin/main의 최신 상태 가져오기
          git fetch origin main

          # temp-push 브랜치의 첫 번째 새 커밋 확인
          NEW_COMMIT=$(git rev-list --reverse origin/main..temp-push | head -n 1)

          if [ -n "$NEW_COMMIT" ]; then
            echo "Found new commit: $NEW_COMMIT"

            # 새 커밋만 포함된 temp-main 브랜치를 생성
            git checkout -b temp-main $NEW_COMMIT

            # main 브랜치로 강제 푸시
            git push origin temp-main:main --force-with-lease
          else
            echo "No new commits to push!"
          fi
