name: 1일 1커밋 자동화

on:
  schedule:
    # 매일 오전 12시에 실행 (UTC 기준) : 분 시 일 월 요일
    - cron: "0 0 * * *"

jobs:
  push-daily-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config user.name "DevNerd"
          git config user.email "krsy0411@naver.com"

      - name: Push one commit per day
        run: |
          # origin/main에 없는 첫 번째 커밋을 찾아서 푸시
          git fetch origin main
          NEW_COMMIT=$(git rev-list --reverse origin/main..HEAD | head -n 1)
          if [ -n "$NEW_COMMIT" ]; then
            git reset --hard $NEW_COMMIT
            git push origin main
          else
            echo "No new commits to push!"
          fi
